//UNIT
//fetch list of units
export const FETCH_UNITS = "FETCH_UNITS";
export const FETCH_UNITS_SUCCESS = "FETCH_UNITS_SUCCESS";
export const FETCH_UNITS_FAILURE = "FETCH_UNITS_FAILURE";

//fetch single unit
export const FETCH_UNIT = "FETCH_UNIT";
export const FETCH_UNIT_SUCCESS = "FETCH_UNIT_SUCCESS";
export const FETCH_UNIT_FAILURE = "FETCH_UNIT_FAILURE";

export const ADD_UNIT = "ADD_UNIT";
export const ADD_UNIT_SUCCESS = "ADD_UNIT_SUCCESS";
export const ADD_UNIT_FAILURE = "ADD_UNIT_FAILURE";

export const DELETE_UNIT = "DELETE_UNIT";
export const DELETE_UNIT_SUCCESS = "DELETE_UNIT_SUCCESS";
export const DELETE_UNIT_FAILURE = "DELETE_UNIT_FAILURE";
export const DELETE_UNIT_RESET = "DELETE_UNIT_RESET";

export const UPDATE_UNIT = "UPDATE_UNIT";
export const UPDATE_UNIT_SUCCESS = "UPDATE_UNIT_SUCCESS";
export const UPDATE_UNIT_FAILURE = "UPDATE_UNIT_FAILURE";
export const UPDATE_UNIT_RESET   = "UPDATE_UNIT_RESET";


//INGREDIENT
export const FETCH_INGS = "FETCH_INGS";
export const FETCH_INGS_SUCCESS = "FETCH_INGS_SUCCESS";
export const FETCH_INGS_FAILURE = "FETCH_INGS_FAILURE";

export const FETCH_ING = "FETCH_ING";
export const FETCH_ING_SUCCESS = "FETCH_ING_SUCCESS";
export const FETCH_ING_FAILURE = "FETCH_ING_FAILURE";

export const ADD_ING = "ADD_ING";
export const ADD_ING_SUCCESS = "ADD_ING_SUCCESS";
export const ADD_ING_FAILURE = "ADD_ING_FAILURE";

export const UPDATE_ING = "UPDATE_ING";
export const UPDATE_ING_SUCCESS = "UPDATE_ING_SUCCESS";
export const UPDATE_ING_FAILURE = "UPDATE_ING_FAILURE";

export const DELETE_ING = "DELETE_ING";
export const DELETE_ING_SUCCESS = "DELETE_ING_SUCCESS";
export const DELETE_ING_FAILURE = "DELETE_ING_FAILURE";

//Dish
export const FETCH_DISHES = "FETCH_DISHES";
export const FETCH_DISHES_SUCCESS = "FETCH_DISHES_SUCCESS";
export const FETCH_DISHES_FAILURE = "FETCH_DISHES_FAILURE";

export const FETCH_DISH = "FETCH_DISH";
export const FETCH_DISH_SUCCESS = "FETCH_DISH_SUCCESS";
export const FETCH_DISH_FAILURE = "FETCH_DISH_FAILURE";

export const ADD_DISH = "ADD_DISH";
export const ADD_DISH_SUCCESS = "ADD_DISH_SUCCESS";
export const ADD_DISH_FAILURE = "ADD_DISH_FAILURE";

export const UPDATE_DISH = "UPDATE_DISH";
export const UPDATE_DISH_SUCCESS = "UPDATE_DISH_SUCCESS";
export const UPDATE_DISH_FAILURE = "UPDATE_DISH_FAILURE";

export const DELETE_DISH = "DELETE_DISH";
export const DELETE_DISH_SUCCESS = "DELETE_DISH_SUCCESS";
export const DELETE_DISH_FAILURE = "DELETE_DISH_FAILURE";

//order
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "FETCH_ORDERS_FAILURE";

export const ADD_ORDER = "ADD_ORDER";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILURE = "ADD_ORDER_FAILURE";

export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILURE = "DELETE_ORDER_FAILURE";
